char_list = [
    'Traveler',
    'Albedo',
    'Zhongli',
    'Shibyou',
    'Kaedehara Kazuha',
    'Xiao',
    'Venti',
    'Jean',
    'Shenhe',
    'Eula',
    'Ganyu',
    'Qiqi',
    'Kamisato Ayaka',
    'Yae Miko',
    'Raiden Shogun',
    'Keqing',
    'Alhaitham',
    'Nahida',
    'Tighnari',
    'Yelan',
    'Mona',
    'Tartaglia',
    'Dehya',
    'Yoimiya',
    'Klee',
    'Diluc',
    'Yun Jin',
    'Gorou',
    'Noelle',
    'Ningguang',
    'Shikanoin Heizou',
    'Sayu',
    'Sucrose',
    'Mika',
    'Layla',
    'Rosaria',
    'Diona',
    'Chongyun',
    'Kaeya',
    'Dori',
    'Kuki Shinobu',
    'Kujou Sara',
    'Fischl',
    'Beidou',
    'Razor',
    'Lisa',
    'Kaveh',
    'Collei',
    'Candace',
    'Xingqiu',
    'Barbara',
    'Thoma',
    'Yanfei',
    'Xinyan',
    'Bennett',
    'Xiangling',
    'Amber'
]
